[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs>=0.5",
  "hatchling>=1.32.4",
]

[project]
name = "pre-commit-uv"
description = "Run pre-commit with uv"
readme = "README.md"
keywords = [
  "format",
  "pyproject",
]
license.file = "LICENSE.txt"
authors = [
  { name = "Bernat Gabor", email = "gaborjbernat@gmail.com" },
]
requires-python = ">=3.11"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dynamic = [
  "version",
]
dependencies = [
  "pre-commit>=4.6.2",
  "uv>=0.12.22",
]
urls."Bug Tracker" = "https://github.com/tox-dev/pre-commit-uv/issues"
urls."Source Code" = "https://github.com/tox-dev/pre-commit-uv"
urls.Changelog = "https://github.com/tox-dev/pre-commit-uv/releases"
urls.Documentation = "https://github.com/tox-dev/pre-commit-uv/"

[dependency-groups]
dev = [
  { include-group = "lint" },
  { include-group = "pkg-meta" },
  { include-group = "test" },
  { include-group = "type" },
]
test = [
  "covdefaults>=2.3",
  "pytest>=9.1.1",
  "pytest-cov>=7.1",
  "pytest-mock>=3.16",
]
type = [
  "ty>=0.0.84",
  { include-group = "test" },
]
lint = [
  "pre-commit-uv>=4.2",
]
pkg-meta = [
  "check-wheel-contents>=0.6.3",
  "twine>=7",
  "uv>=0.12.22",
]

[tool.hatch]
version.source = "vcs"
build.dev-mode-dirs = [
  "src",
]
build.targets.sdist.include = [
  "/src",
  "/tests",
  "tox.ini",
]
build.targets.wheel.only-include = [ "src" ]
build.targets.wheel.sources = [ "src" ]

[tool.ruff]
line-length = 120
format.preview = true
format.docstring-code-line-length = 100
format.docstring-code-format = true
lint.select = [
  "ALL",
]
lint.ignore = [
  "any-type",                                  # allow Any as type annotation
  "CPY",                                       # No copyright statements
  "docstring-missing-exception",               # not working with Sphinx
  "hardcoded-bind-all-interfaces",             # Possible binding to all interfaces
  "incorrect-blank-line-before-class",         # `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible
  "missing-trailing-comma",                    # Conflict with formatter
  "multi-line-summary-first-line",             # `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible
  "non-empty-init-module",                     # `__init__` module should only contain docstrings and re-exports
  "single-line-implicit-string-concatenation", # Conflict with formatter
]
lint.per-file-ignores."tests/**/*.py" = [
  "assert",                        # asserts allowed in tests...
  "D",                             # don"t care about documentation in tests
  "FBT",                           # don"t care about booleans as positional arguments in tests
  "implicit-namespace-package",    # no implicit namespace
  "import-private-name",           # private import
  "magic-value-comparison",        # Magic value used in comparison, consider replacing with a constant variable
  "S",                             # `subprocess` call: check for execution of untrusted input
  "too-many-arguments",            # any number of arguments in tests
  "too-many-positional-arguments", # any number of arguments in tests
]
lint.isort = { known-first-party = [
  "pre_commit_uv",
], required-imports = [
  "from __future__ import annotations",
] }
lint.preview = true

[tool.codespell]
builtin = "clear,usage,en-GB_to_en-US"
count = true

[tool.pyproject-fmt]
max_supported_python = "3.15"

[tool.ty]
environment.python-version = "3.15"

[tool.pytest]
ini_options.testpaths = [
  "tests",
]

[tool.coverage]
run.parallel = true
run.plugins = [
  "covdefaults",
]
paths.source = [
  "src",
  ".tox/*/.venv/lib/*/site-packages",
  ".tox\\*\\.venv\\Lib\\site-packages",
  ".tox/*/lib/*/site-packages",
  ".tox\\*\\Lib\\site-packages",
  "**/src",
  "**\\src",
]
report.fail_under = 63
html.show_contexts = true
html.skip_covered = false
